
services:
  nginx:
    build:
      context: ./docker/nginx/
    container_name: ${APP_DIR}-nginx
    volumes:
      - ./:/var/www/${APP_NAME}:delegated
      - ./docker/nginx/templates:/etc/nginx/templates:rw,cached
      - ./docker/nginx/configs/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /var/www/${APP_NAME}
    environment:
      APP_DIR: ${APP_NAME}
    depends_on:
      - php
      - mysql
    ports:
      - ${APP_PORT}:80

  php:
    build:
      context: ./docker/php/
    container_name: ${APP_DIR}-php
    volumes:
      - ./:/var/www/${APP_NAME}:delegated
      - ./docker/php/configs/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/${APP_DIR}
    environment:
      PHP_IDE_CONFIG: serverName=${APP_DIR}
    ports:
      - 9000

  mysql:
    build:
      context: ./docker/mysql/
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mysql/db/:/var/lib/mysql
      - ./docker/mysql/dump/:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 53306:3306

  node:
    build:
      context: ./docker/node/
    container_name: ${APP_DIR}-node
    volumes:
      - ./:/var/www/${APP_NAME}
    working_dir: /var/www/${APP_DIR}
